-- Bảng đơn hàng: lưu thông tin đơn + kết quả sau thanh toán.
CREATE TABLE orders (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref                VARCHAR(64)  NOT NULL,
    idempotency_key          VARCHAR(128) NOT NULL,
    product_name             VARCHAR(255),
    amount                   BIGINT,
    quantity                 BIGINT,
    currency                 VARCHAR(16),
    mode                     VARCHAR(32),
    status                   VARCHAR(32)  NOT NULL,
    stripe_session_id        VARCHAR(255),
    stripe_session_url       TEXT,
    stripe_payment_intent_id VARCHAR(255),
    amount_total             BIGINT,
    customer_email           VARCHAR(255),
    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL
);

-- Khóa chống trùng: một idempotency key = một đơn duy nhất.
-- Retry cùng key sẽ không tạo đơn/phiên thanh toán mới.
CREATE UNIQUE INDEX ux_orders_idempotency_key ON orders (idempotency_key);
CREATE INDEX ix_orders_order_ref            ON orders (order_ref);
CREATE INDEX ix_orders_session_id           ON orders (stripe_session_id);
CREATE INDEX ix_orders_payment_intent_id    ON orders (stripe_payment_intent_id);

-- Bảng chống xử lý webhook trùng: Stripe có thể gửi lại cùng một event.
CREATE TABLE processed_webhook_events (
    event_id     VARCHAR(255) PRIMARY KEY,
    type         VARCHAR(128),
    processed_at TIMESTAMP NOT NULL
);
